//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumThread
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumThread()
        {
            this.ThreadReplies = new HashSet<ThreadReply>();
        }
    
        public long ID { get; set; }
        public long TopicID { get; set; }
        public long CreatedBy { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThreadReply> ThreadReplies { get; set; }
    }
}
