//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstantMessage()
        {
            this.InstantMessageReplies = new HashSet<InstantMessageReply>();
        }
    
        public long ID { get; set; }
        public string Body { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long ToUser { get; set; }
        public long FromUser { get; set; }
        public Nullable<bool> IsNew { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantMessageReply> InstantMessageReplies { get; set; }
    }
}
