//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{
    using System;

    public partial class LoginAttempt
    {
        public long ID { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
