//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
