//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{

    public partial class Profile
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Interests { get; set; }
        public int PostCount { get; set; }
        public string Location { get; set; }
        public string AvatarName { get; set; }
    
        public virtual User User { get; set; }
    }
}
