//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.DataModel
{
    using System;

    public partial class ThreadReply
    {
        public long ID { get; set; }
        public long ForumThreadID { get; set; }
        public long UserID { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual ForumThread ForumThread { get; set; }
    }
}
